CREATE TABLE IF NOT EXISTS Users(
userId INTEGER PRIMARY KEY AUTOINCREMENT,
firstName TEXT,
lastName TEXT,
tipoDoc TEXT,
documento TEXT,
aceptaTerminos TEXT,
ssno TEXT,
imageUrl TEXT,
metadatos TEXT,
empresa NUMERIC,
regional NUMERIC,
instalacion NUMERIC,
origen NUMERIC,
step_enrol NUMERIC);
